### PR TITLE
Bump cumulusci to version 3.32.0

### PR DESCRIPTION
**Pull request by jofsky**

### CODE REVIEW

**Review by codexmarcel — APPROVED** [review]
LGTM

**Review by davisagli — APPROVED** [review]
You don't need to ask for review on these as long as the build passes.

**Comment by jofsky** [comment]
@davisagli looks like the tests are failing any ideas?

**Comment by davisagli** [comment]
@jofsky hmm, docutils got removed. I readded it manually and will follow up to figure out why it went missing.

**Pull request merged**
